# Sphinx component subdirectories
include("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/vxworks-shim/vxworks-shim.cmake")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/ADC/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/ADCPacket/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/FPGADriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/FpgaGpioDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/FPGASPIDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/GPIODriver")
#add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/GPIOInterruptHandler")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/GPIOInterruptRouter")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/GPTimerDriver/")
#add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/NOR")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/NORFlashDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/NORFlashManager")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/NORFlashMgrWorker")
#add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/OCM")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/SphinxTime/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/SphinxUartOnboardDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/SPIDriverGeneric")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/SPWDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/SPWManager")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/TrapRegistry")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/UartDriver")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Util")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/WakeupManager")






#ports
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/Apid/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_Claim/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_ReadControl/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_ReadCounter/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_ReadReload/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_Unclaim/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_WriteControl/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_WriteCounter/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/GPTimerDriver_WriteReload/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NOR_done/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_BR/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_BW/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_Cancel/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_ChecksumDone/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_EraseBankAddr/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_EraseBankNumber/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_GetSize/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_ReadB/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_Reset/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_RW/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_Verify/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/NORFlash_WriteB/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxFPGASPI_RW/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxGPIO_ReadPin/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxGPIO_Setup/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxGPIO_WritePin/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxMem_RW/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxRegRead/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxRegWrite/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_Claim/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_configSlave/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_Configure/")
#add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_RW/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_RW16_Generic/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_RW32_Generic/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_RW_Generic/")
#add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_SS_Release/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPI_Unclaim/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_ReadRMAP/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_SendRequest/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_SendRequestAsync/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_SetParam/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_Status/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_StatusOut/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_Toggle/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_Trigger/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxSPW_WriteRMAP/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxTimeVal/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxUart_bytesUsedPort/")



add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxUart_readPort/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxUart_writePort/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/SphinxUartBuffer/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Ports/WakeupManager_Sleep/")

add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Os/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/UtilityFunctions/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Random/")
add_fprime_subdirectory("${CMAKE_CURRENT_LIST_DIR}/fprime-sphinx-drivers/Test/")

