#ifndef SPHINX_DRV_OCM
#define SPHINX_DRV_OCM

#if defined(BUILD_SPHINX)
#define SPHINX_OCM_BASE_ADDR 0xA0000000
#define SPHINX_OCM_HIGH_ADDR 0xA0030000

#elif defined(BUILD_GR712DEV)
#define SPHINX_OCM_BASE_ADDR 0x80100000
#define SPHINX_OCM_HIGH_ADDR 0x801000FC

#else
#define SPHINX_OCM_BASE_ADDR 0x0
#define SPHINX_OCM_HIGH_ADDR 0xFFFF
#endif


#define SPHINX_OCM_VALID_FLAG_ADDR SPHINX_OCM_BASE_ADDR
#define SPHINX_OCM_VALID_FLAG_VALUE 0xa5b5c560

#define SPHINX_OCM_BOOT_COUNT_ADDR             (SPHINX_OCM_BASE_ADDR + 0x4)
#define SPHINX_OCM_UTIL_PART_FLAG_ADDR         (SPHINX_OCM_BASE_ADDR + 0x8)
#define SPHINX_OCM_ENG_PART_FLAG_ADDR          (SPHINX_OCM_BASE_ADDR + 0xC)
#define SPHINX_OCM_SCI_PART_FLAG_ADDR          (SPHINX_OCM_BASE_ADDR + 0x10)
#define SPHINX_OCM_SEQ_PART_FLAG_ADDR          (SPHINX_OCM_BASE_ADDR + 0x14)

#define SPHINX_OCM_BSEQ_ST_CANCEL_FLAG_ADDR    (SPHINX_OCM_BASE_ADDR + 0x18)
#define SPHINX_OCM_STARTUP_CHECKSUM_ADDR      (SPHINX_OCM_BASE_ADDR + 0x1C)


#define SPHINX_OCM_PWR_SW_BASE (SPHINX_OCM_BASE_ADDR + 0x100)
#define SPHINX_OCM_PWR_SW_END (SPHINX_OCM_PWR_SW_BASE + 0x100)
#define SPHINX_OCM_PWR_SW_RECORD_SIZE 0xc

#define SPHINX_OCM_FATAL_BASE (SPHINX_OCM_PWR_SW_END + 0x100)
#define SPHINX_OCM_FATAL_END ((SPHINX_OCM_HIGH_ADDR - SPHINX_OCM_BASE_ADDR)/2 + SPHINX_OCM_BASE_ADDR)

#endif /* SPHINX_DRV_SRAM */
